name: Latest Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup .NET 10
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Disable debug in appsettings.json for release
      run: |
        jq '.AppInfo.Debug = false' FluxProDisplay/appsettings.json > tmp.json && mv tmp.json FluxProDisplay/appsettings.json

    - name: Build and publish
      run: dotnet publish -c Release -r win-x64 -p:SelfContained=false -p:Version=${GITHUB_REF#refs/tags/v} --property:PublishDir=$(pwd)/publish

    - name: Zip published output
      run: |
        cd $(pwd)/publish
        zip -r ../antecfluxprodisplay.zip .
        cd ..

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v3
      with:
        files: antecfluxprodisplay.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
